DROP TABLE IF EXISTS jugador;
DROP TABLE IF EXISTS equipo;

CREATE TABLE equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    ciudad VARCHAR(255),
    conferencia VARCHAR(255),
    anio_fundacion INT
);

CREATE TABLE jugador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    posicion VARCHAR(255) NOT NULL,
    dorsal INT NOT NULL,
    altura DOUBLE,
    equipo_id BIGINT,
    FOREIGN KEY (equipo_id) REFERENCES equipo(id)
);